version: '3.4' # specify docker-compose version

networks:
  part-library:

# Define the services/containers to be run
services:
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db # This is where your volume will persist.
    networks:
      - part-library

volumes:
  mongo_volume: